{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5d1db5e9",
   "metadata": {},
   "source": [
    "## Introduction\n",
    "#### Scientific Question\n",
    "- How does the changes in gene FKBP5 associated with depressive diseases in the human body?\n",
    "\n",
    "#### Background of Gene FKBP5\n",
    "- FKBP5, also known as FK506 binding protein 5, is an important modulator of stress response. The gene FKBP5 acts as a co-chaperone that modulates the glucocorticoid receptor activity in response to stressors and other cellular processes in the brain and periphery (Zannas et al. 2016)\n",
    "\n",
    "#### Scientific Hypothesis: \n",
    "- If the gene FKBP5 is associated with depression, then there will be changes in the gene FKBP5 when the human body is experiencing depressive diseases.\n",
    "\n",
    "#### Description of Analyses and Data\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d0ea3cd1",
   "metadata": {},
   "source": [
    "## Loading in Packages"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "937cc808",
   "metadata": {},
   "source": [
    "## Performing Bioinformatics Analysis\n",
    "- Pairwise Alignment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "3037c74c",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (1928216380.py, line 13)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/ipykernel_23090/1928216380.py\"\u001b[0;36m, line \u001b[0;32m13\u001b[0m\n\u001b[0;31m    for match in alignments:\u001b[0m\n\u001b[0m                           ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "# Import libraries\n",
    "from Bio import pairwise2\n",
    "from Bio.Seq import Seq\n",
    "  \n",
    "# Creating sample sequences\n",
    "FKBP5_sequence = Seq(\"FKBP5_datasets (1).zip\")\n",
    "seq2 = Seq(\n",
    "  \n",
    "# Finding similarities\n",
    "alignments = pairwise2.align.globalxx(FKBP5_sequence, seq2)\n",
    "  \n",
    "# Showing results\n",
    "for match in alignments:\n",
    "    print(match)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "eab287f8",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "both sequences must be of the same type, either string/sequence object or list. Gap character must fit the sequence type (string or list)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/Bio/pairwise2.py\u001b[0m in \u001b[0;36m_align\u001b[0;34m(sequenceA, sequenceB, match_fn, gap_A_fn, gap_B_fn, penalize_extend_when_opening, penalize_end_gaps, align_globally, gap_char, force_generic, score_only, one_alignment_only)\u001b[0m\n\u001b[1;32m    533\u001b[0m         \u001b[0msequenceA\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mgap_char\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 534\u001b[0;31m         \u001b[0msequenceB\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mgap_char\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    535\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'type' and 'str'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/ipykernel_23090/285247493.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     11\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0;31m# Finding similarities\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 13\u001b[0;31m \u001b[0malignments\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpairwise2\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0malign\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mglobalxx\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mFKBP5_sequence\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mseq2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0;31m# Showing results\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/Bio/pairwise2.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, *args, **keywds)\u001b[0m\n\u001b[1;32m    491\u001b[0m             \u001b[0;34m\"\"\"Call the alignment instance already created.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    492\u001b[0m             \u001b[0mkeywds\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkeywds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 493\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0m_align\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mkeywds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    494\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    495\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__getattr__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mattr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/Bio/pairwise2.py\u001b[0m in \u001b[0;36m_align\u001b[0;34m(sequenceA, sequenceB, match_fn, gap_A_fn, gap_B_fn, penalize_extend_when_opening, penalize_end_gaps, align_globally, gap_char, force_generic, score_only, one_alignment_only)\u001b[0m\n\u001b[1;32m    534\u001b[0m         \u001b[0msequenceB\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mgap_char\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    535\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 536\u001b[0;31m         raise TypeError(\n\u001b[0m\u001b[1;32m    537\u001b[0m             \u001b[0;34m\"both sequences must be of the same type, either \"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    538\u001b[0m             \u001b[0;34m\"string/sequence object or list. Gap character must \"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: both sequences must be of the same type, either string/sequence object or list. Gap character must fit the sequence type (string or list)"
     ]
    }
   ],
   "source": [
    "#or we can also use\n",
    "\n",
    "# Import libraries\n",
    "from Bio import pairwise2\n",
    "from Bio.Seq import Seq\n",
    "from Bio.pairwise2 import format_alignment\n",
    "  \n",
    "# Creating sqmple sequences\n",
    "FKBP5_sequence = Seq(\"FKBP5_datasets (1).zip\")\n",
    "seq2 = Seq\n",
    "  \n",
    "# Finding similarities\n",
    "alignments = pairwise2.align.globalxx(FKBP5_sequence, seq2)\n",
    "  \n",
    "# Showing results\n",
    "for alignment in alignments:\n",
    "    print(format_alignment(*alignment))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e350ac09",
   "metadata": {},
   "source": [
    "## Plotting The Results\n",
    "- P-values\n",
    "- Phylogenetic Clustering"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "a5653a94",
   "metadata": {},
   "outputs": [],
   "source": [
    "from scipy import stats\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "04606409",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting treeCl\n",
      "  Downloading treeCl-0.1.38.tar.gz (515 kB)\n",
      "\u001b[K     |████████████████████████████████| 515 kB 4.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: biopython in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (1.78)\n",
      "Requirement already satisfied: cython>=0.19.0 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (0.29.24)\n",
      "Collecting dendropy>=4.0.0\n",
      "  Downloading DendroPy-4.5.2.tar.gz (15.2 MB)\n",
      "\u001b[K     |████████████████████████████████| 15.2 MB 22.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting fastcluster\n",
      "  Downloading fastcluster-1.2.6-cp39-cp39-macosx_10_9_x86_64.whl (40 kB)\n",
      "\u001b[K     |████████████████████████████████| 40 kB 5.9 MB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting futures\n",
      "  Downloading futures-3.0.5.tar.gz (25 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/amyhuynh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_12a833cc054e474fa9d01d7a842369d3/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_12a833cc054e474fa9d01d7a842369d3/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-pip-egg-info-df45r2hr\n",
      "         cwd: /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_12a833cc054e474fa9d01d7a842369d3/\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_12a833cc054e474fa9d01d7a842369d3/concurrent/futures/__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_12a833cc054e474fa9d01d7a842369d3/concurrent/futures/_base.py\", line 357\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/55/db/97c1ca37edab586a1ae03d6892b6633d8eaa23b23ac40c7e5bbc55423c78/futures-3.0.5.tar.gz#sha256=0542525145d5afc984c88f914a0c85c77527f65946617edb5274f72406f981df (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading futures-3.0.4.tar.gz (25 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/amyhuynh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_b8dd3679165b4a0e929ea0cae1f8b6ea/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_b8dd3679165b4a0e929ea0cae1f8b6ea/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-pip-egg-info-i1su7f_1\n",
      "         cwd: /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_b8dd3679165b4a0e929ea0cae1f8b6ea/\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_b8dd3679165b4a0e929ea0cae1f8b6ea/concurrent/futures/__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_b8dd3679165b4a0e929ea0cae1f8b6ea/concurrent/futures/_base.py\", line 357\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/8d/73/b5fff618482bc06c9711e7cdc0d5d7eb1904d35898f48f2d7f9696b08bef/futures-3.0.4.tar.gz#sha256=19485d83f7bd2151c0aeaf88fbba3ee50dadfb222ffc3b66a344ef4952b782a3 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading futures-3.0.3.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/amyhuynh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_23d88d54138e4b7e989a5a9dd96c1b45/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_23d88d54138e4b7e989a5a9dd96c1b45/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-pip-egg-info-1yfybbdu\n",
      "         cwd: /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_23d88d54138e4b7e989a5a9dd96c1b45/\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_23d88d54138e4b7e989a5a9dd96c1b45/concurrent/futures/__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_23d88d54138e4b7e989a5a9dd96c1b45/concurrent/futures/_base.py\", line 355\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4c/dc/f9473006d4c9c52d4a4e977173fbcbfb1a8ef3a57e32e885edf994fd4a45/futures-3.0.3.tar.gz#sha256=2fe2342bb4fe8b8e217f0d21b5921cbe5408bf966d9f92025e707e881b198bed (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading futures-3.0.2.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/amyhuynh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_38d166e045e74e8fb1e9481f8e01798d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_38d166e045e74e8fb1e9481f8e01798d/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-pip-egg-info-izi5e3zm\n",
      "         cwd: /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_38d166e045e74e8fb1e9481f8e01798d/\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_38d166e045e74e8fb1e9481f8e01798d/concurrent/futures/__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_38d166e045e74e8fb1e9481f8e01798d/concurrent/futures/_base.py\", line 355\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f8/e7/fc0fcbeb9193ba2d4de00b065e7fd5aecd0679e93ce95a07322b2b1434f4/futures-3.0.2.tar.gz#sha256=dc3fc91508e49e0fd2f8625f0132d16e49c80f882e7e1d565c56b0d5dfbae257 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading futures-3.0.1.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/amyhuynh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_eec3a66c76444c44ac624a7667e282b7/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_eec3a66c76444c44ac624a7667e282b7/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-pip-egg-info-xrwl7iuc\n",
      "         cwd: /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_eec3a66c76444c44ac624a7667e282b7/\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_eec3a66c76444c44ac624a7667e282b7/concurrent/futures/__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_eec3a66c76444c44ac624a7667e282b7/concurrent/futures/_base.py\", line 355\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/b2/2c/6b6a57379e47031c6f52e625e0e2b8f6702a8d1f61b6e0daee391e82c187/futures-3.0.1.tar.gz#sha256=f78f2ef458639d72a625cf9c7643cf5442bb222ac11c12bcc445c6ad1cd862e2 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading futures-3.0.0.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/amyhuynh/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_512b3d63a4a446ddb7360fcbc8602694/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_512b3d63a4a446ddb7360fcbc8602694/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-pip-egg-info-0kscyscu\n",
      "         cwd: /private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_512b3d63a4a446ddb7360fcbc8602694/\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"/Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_512b3d63a4a446ddb7360fcbc8602694/concurrent/futures/__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"/private/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/pip-install-nq_06q6x/futures_512b3d63a4a446ddb7360fcbc8602694/concurrent/futures/_base.py\", line 354\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ea/c9/35287369718fc05059e7a9d0d73c53745fe981010b4185b3858e7d46eff1/futures-3.0.0.tar.gz#sha256=d9cd7bb09aa01f0e4940af64c31fbd7045098b7b4354420d7838ea39e8b86ee3 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Downloading futures-2.2.0-py2.py3-none-any.whl (16 kB)\n",
      "Requirement already satisfied: ipython in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (7.29.0)\n",
      "Requirement already satisfied: matplotlib in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (3.4.3)\n",
      "Requirement already satisfied: nose in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (1.3.7)\n",
      "Requirement already satisfied: numpy in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (1.20.3)\n",
      "Requirement already satisfied: pandas in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (1.3.4)\n",
      "Collecting phylo_utils==0.0.5\n",
      "  Downloading phylo_utils-0.0.5.tar.gz (14 kB)\n",
      "Collecting progressbar-latest==2.4\n",
      "  Downloading progressbar-latest-2.4.tar.gz (10 kB)\n",
      "Requirement already satisfied: PyYaml in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (6.0)\n",
      "Requirement already satisfied: scipy in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (1.7.1)\n",
      "Requirement already satisfied: scikit-learn in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from treeCl) (0.24.2)\n",
      "Collecting tree_distance>=1.0.6\n",
      "  Downloading tree_distance-1.0.7.tar.gz (863 kB)\n",
      "\u001b[K     |████████████████████████████████| 863 kB 14.9 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: setuptools in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from dendropy>=4.0.0->treeCl) (58.0.4)\n",
      "Requirement already satisfied: decorator in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (5.1.0)\n",
      "Requirement already satisfied: matplotlib-inline in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (0.1.2)\n",
      "Requirement already satisfied: jedi>=0.16 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (0.18.0)\n",
      "Requirement already satisfied: pickleshare in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (0.7.5)\n",
      "Requirement already satisfied: appnope in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (0.1.2)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (3.0.20)\n",
      "Requirement already satisfied: backcall in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (0.2.0)\n",
      "Requirement already satisfied: pygments in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (2.10.0)\n",
      "Requirement already satisfied: pexpect>4.3 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (4.8.0)\n",
      "Requirement already satisfied: traitlets>=4.2 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from ipython->treeCl) (5.1.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython->treeCl) (0.8.2)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython->treeCl) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->treeCl) (0.2.5)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->treeCl) (3.0.4)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->treeCl) (0.10.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->treeCl) (1.3.1)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->treeCl) (2.8.2)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->treeCl) (8.4.0)\n",
      "Requirement already satisfied: six in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->treeCl) (1.16.0)\n",
      "Requirement already satisfied: pytz>=2017.3 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from pandas->treeCl) (2021.3)\n",
      "Requirement already satisfied: joblib>=0.11 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn->treeCl) (1.1.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/amyhuynh/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn->treeCl) (2.2.0)\n",
      "Building wheels for collected packages: treeCl, phylo-utils, progressbar-latest, dendropy, tree-distance\n",
      "  Building wheel for treeCl (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for treeCl: filename=treeCl-0.1.38-cp39-cp39-macosx_10_9_x86_64.whl size=295537 sha256=a702d3a1d7d2414fde7081584fe46ac69777a4a642936e86868e5e03e003edb7\n",
      "  Stored in directory: /Users/amyhuynh/Library/Caches/pip/wheels/ce/3c/1d/3ce6d8581821fc299b8450e8a3f28f526426f912ac01492a98\n",
      "  Building wheel for phylo-utils (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for phylo-utils: filename=phylo_utils-0.0.5-cp39-cp39-macosx_10_9_x86_64.whl size=109969 sha256=7ec469526a1b800a5ff5d4c332135aaaf7e7caaccefa8bda9fc53fd8b92d9f0f\n",
      "  Stored in directory: /Users/amyhuynh/Library/Caches/pip/wheels/e5/94/e2/920dfcff7a09c4b2b8cd7f6f7f32d726a50c55a331d47f408e\n",
      "  Building wheel for progressbar-latest (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for progressbar-latest: filename=progressbar_latest-2.4-py3-none-any.whl size=12189 sha256=9a4943f4c52c53b0fdd884f2a2b10b5c4428afb35be90b2107d3737da67ecbd9\n",
      "  Stored in directory: /Users/amyhuynh/Library/Caches/pip/wheels/dc/10/32/bfd612a01bf21fe74611b9786434e80da6952df8ea435f71b8\n",
      "  Building wheel for dendropy (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for dendropy: filename=DendroPy-4.5.2-py3-none-any.whl size=453171 sha256=03a1d93b17e9a53e3f806e1831e4dfc1147bbc36e7798d2be107d55e276825eb\n",
      "  Stored in directory: /Users/amyhuynh/Library/Caches/pip/wheels/21/c6/01/b2bcc1c029788d785673c27660b0f9ca0792a7b2bf9fb48bbf\n",
      "  Building wheel for tree-distance (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for tree-distance: filename=tree_distance-1.0.7-cp39-cp39-macosx_10_9_x86_64.whl size=149560 sha256=a9559b3b5b2f608d1b69e8b76313f67a15ff3c6660743e25d40ee34739ed767d\n",
      "  Stored in directory: /Users/amyhuynh/Library/Caches/pip/wheels/be/27/f9/635c9fa6acfd53942723163aeb91be98179552656e4a3f6dd6\n",
      "Successfully built treeCl phylo-utils progressbar-latest dendropy tree-distance\n",
      "Installing collected packages: dendropy, tree-distance, progressbar-latest, phylo-utils, futures, fastcluster, treeCl\n",
      "Successfully installed dendropy-4.5.2 fastcluster-1.2.6 futures-2.2.0 phylo-utils-0.0.5 progressbar-latest-2.4 tree-distance-1.0.7 treeCl-0.1.38\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install treeCl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "eaeee13b",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'ete2'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/ipykernel_23090/1147495188.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mete2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mClusterTree\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'ete2'"
     ]
    }
   ],
   "source": [
    "from ete2 import ClusterTree"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "747301bc",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (1370244763.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"/var/folders/nc/09cx79nn5xz69vj163ls6z8m0000gn/T/ipykernel_23090/1370244763.py\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    pip3 install --user git+https://github.com/scwatts/treeclust.git\u001b[0m\n\u001b[0m         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "pip3 install --user git+https://github.com/scwatts/treeclust.git"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "a9358843",
   "metadata": {},
   "outputs": [],
   "source": [
    "from Bio import Phylo, AlignIO\n",
    "from Bio.Phylo.TreeConstruction import DistanceCalculator, DistanceTreeConstructor"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "198494ff",
   "metadata": {},
   "source": [
    "## Analysis of Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "48370af4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
